### ISSUE TITLE
Migrate to scss

### ISSUE THREAD

**Issue by diegoaceneves** [diegoaceneves/bootstrap-fontawesome#1]
Migrate from less to scss

**Comment by sangamcse** [comment]
I'll do it.

**Comment by mateuspv** [comment]
FIY: http://less2scss.awk5.com/  and https://www.npmjs.com/package/less-scss-convertor

**Comment by diegoaceneves** [comment]
hi @sangamcse , this issue has been resolved but has not yet been commited, thank you for your time.

**Comment by diegoaceneves** [comment]
hi @mateuspv , bootstrap n' font-awesome release a both scss sources, thank you for your time.
